CITY_CODES = {
    'SA': {
        'country_code': 'KSA',
        'city_codes': {
            "Aba Alworood": "ELQ001",
            "Abayt": "TUU001",
            "Abha": "AHB",
            "Abiar Al Mashi": "MED001",
            "Abo Halaefa": "JED001",
            "Abqaiq": "DMM001",
            "Abu Ajram": "AJF001",
            "Abu Al Arj": "GIZ001",
            "Abu Arish": "GIZ002",
            "Abu Arradeef": "GIZ003",
            "Abu Dhiba": "MED002",
            "Abu Hajar": "GIZ004",
            "Abu Haramel": "ULH002",
            "Abu Muloh": "ABT001",
            "Abu Rakah": "TUU002",
            "Abu Rakh": "TIF001",
            "Ad Dalfaah": "ELQ002",
            "Ad Darb": "GIZ005",
            "Ad Dilam": "RUH001",
            "Ad Diriyah": "RUH002",
            "Ad Dubaiyah": "RUH003",
            "Ad Dumayriyah": "MED003",
            "Addayer": "GIZ006",
            "Adham": "ABT002",
            "Afif": "DWD002",
            "Afqara": "DWD003",
            "Afraa": "BHH001",
            "Ahad Al Masarihah": "GIZ007",
            "Ahad Bani Zayd": "ABT003",
            "Ahad Rafidah": "AHB003",
            "Ain Al Nakhal": "HOF019",
            "Ain Dar": "DMM003",
            "Al 'Adhiriyah": "HBT001",
            "Al 'Uwainid": "RUH057",
            "Al Abar": "MAC001",
            "Al Abwa": "JED002",
            "Al Abyar": "JED003",
            "Al Adari": "AJF028",
            "Al Ahmar": "WAE001",
            "Al Ais": "YNB001",
            "Al Aithmah": "MED004",
            "Al Ajfar": "HAS001",
            "Al Akhal": "MED005",
            "Al Amaaria": "RUH005",
            "Al Amar": "ELQ003",
            "Al Amlah": "WAE002",
            "Al Amoah": "AHB004",
            "Al Aqiq": "ABT004",
            "Al Aradiyah": "HAS002",
            "Al Araq": "GIZ008",
            "Al Aridhah": "GIZ009",
            "Al Arin": "AHB005",
            "Al Arjain": "GIZ010",
            "Al Aroos": "GIZ011",
            "Al Artawi": "RUH063",
            "Al Artawiyah": "ELQ005",
            "Al Aseelh": "GIZ012",
            "Al Ashah": "GIZ013",
            "Al Assiyah": "ELQ058",
            "Al Atawilah": "ABT005",
            "Al Atheeb": "ULH003",
            "Al Augdah": "GIZ014",
            "Al Awamer": "ABT006",
            "Al Awshaziyah": "HAS003",
            "Al Azaherah": "ABT007",
            "Al Bad'": "TUU003",
            "Al Badawi": "GIZ015",
            "Al Badayea": "ELQ006",
            "Al Badi Al Qarafi": "GIZ016",
            "Al Badie Al Janobi": "WAE003",
            "Al Badie Al Shamali": "WAE004",
            "Al Baha": "ABT",
            "Al Baheem": "AHB006",
            "Al Barakah": "YNB002",
            "Al Barzah": "MAC002",
            "Al Bashair": "AHB007",
            "Al Bashayer": "BHH002",
            "Al Batha": "HOF020",
            "Al Batilah": "AHB009",
            "Al Bijadyah": "DWD004",
            "Al Birk": "GIZ017",
            "Al Birkah": "HAS004",
            "Al Bkhtah Central": "GIZ018",
            "Al Bkhtah North": "GIZ019",
            "Al Bkhtah South": "GIZ020",
            "Al Braber": "MAC003",
            "Al Bukayriyah": "ELQ007",
            "Al Butayn": "ELQ008",
            "Al Dagharir": "GIZ021",
            "Al Dhabyah": "GIZ022",
            "Al Dhahreyah": "ELQ009",
            "Al Dheelah": "MED007",
            "Al Disah": "TUU004",
            "Al Dughaimiyah": "HOF021",
            "Al Dulaymiyah": "ELQ010",
            "Al Duraeah": "GIZ023",
            "Al Duwadimi": "DWD",
            "Al Edabi": "GIZ024",
            "Al Eshash": "MED008",
            "Al Faqa'Ali": "YNB003",
            "Al Faqirah": "MED009",
            "Al Fara": "AHB059",
            "Al Faraah": "TUU005",
            "Al Farhaniyah": "HAS005",
            "Al Farridah": "HBT002",
            "Al Farshah": "AHB010",
            "Al Fatiha": "GIZ025",
            "Al Fatkha": "HAS006",
            "Al Fawwarah": "ELQ011",
            "Al Figrah": "YNB004",
            "Al Furaysh": "MED010",
            "Al Gafrat": "AHB011",
            "Al Gamri": "GIZ026",
            "Al Gawamshah": "GIZ027",
            "Al Ghat": "ELQ013",
            "Al Ghayl": "WAE005",
            "Al Ghazalah": "HAS007",
            "Al Ghulah": "JED004",
            "Al Ghuzlani": "YNB005",
            "Al Gofol": "GIZ028",
            "Al Habeel": "AHB012",
            "Al Hada": "TIF002",
            "Al Haddar": "WAE006",
            "Al Hadidiyah": "ELQ057",
            "Al Hadithah": "URY002",
            "Al Hadror": "GIZ029",
            "Al Hafayer": "HOF001",
            "Al Hait": "HAS008",
            "Al Hajrah": "ABT009",
            "Al Hamad": "URY003",
            "Al Hamrah": "YNB006",
            "Al Haqu": "GIZ030",
            "Al Harajah": "AHB013",
            "Al Haridhah": "GIZ031",
            "Al Hariq": "RUH007",
            "Al Hasamah": "GIZ032",
            "Al Hasuniyyah": "ELQ014",
            "Al Hathera": "GIZ033",
            "Al Hati": "HAS009",
            "Al Hayyaniyah": "HAS010",
            "Al Hazim": "RUH008",
            "Al Hefnah": "RUH009",
            "Al Henakiyah": "MED011",
            "Al Henayah": "GIZ034",
            "Al Hendeyah": "MED048",
            "Al Heno": "MED012",
            "Al Hufayr": "HAS011",
            "Al Hulayfah As Sufla": "HAS012",
            "Al Hulwah": "RUH010",
            "Al Humidah": "TUU006",
            "Al Humiyat": "TIF003",
            "Al Hunayy": "HOF002",
            "Al Husayni": "GIZ035",
            "Al Husayniyah": "EAM001",
            "Al Husayy": "QJB001",
            "Al Huwayd": "HAS013",
            "Al Ijliyah": "WAE007",
            "Al Jabriyah": "HAS014",
            "Al Jadid": "MED013",
            "Al Jadida": "HAS015",
            "Al Jafdor": "MED014",
            "Al Jafer": "MED015",
            "Al Jaizah": "ABT010",
            "Al Jara": "HAS016",
            "Al Jaradiyah": "GIZ036",
            "Al Jarf": "AHB014",
            "Al Jawah": "GIZ037",
            "Al Jawshan": "EAM002",
            "Al Jerisiyah": "MED016",
            "Al Jernafh": "MED017",
            "Al Jialah": "ELQ015",
            "Al Jihfah": "HAS017",
            "Al Jouf": "AJF",
            "Al Ju'Ranah": "MAC005",
            "Al Jubaylah": "RUH011",
            "Al Judaida": "AJF005",
            "Al Judaieen": "GIZ038",
            "Al Jumum": "MAC004",
            "Al Kadarah": "GIZ039",
            "Al Kadhra Al Shamalia": "GIZ040",
            "Al Kadis": "AHB015",
            "Al Kahafah": "HAS018",
            "Al Kamil": "JED005",
            "Al Karbus": "GIZ041",
            "Al Karra": "ABT059",
            "Al Khabbah": "HAS019",
            "Al Khabra": "ELQ016",
            "Al Khadra Al Janoubia": "GIZ042",
            "Al Khalas": "MAC006",
            "Al Khaniq": "EAM003",
            "Al Kharj": "AKH",
            "Al Kharkhir": "EAM004",
            "Al Kharma": "YNB007",
            "Al Kharma Al Shimaliah": "ELQ017",
            "Al Khashabiyah": "GIZ043",
            "Al Khashah": "GIZ044",
            "Al Khasiybah": "ELQ018",
            "Al Khasrah": "DWD005",
            "Al Khitah": "HAS020",
            "Al Khobar": "DMM45",
            "Al Khurma": "TIF004",
            "Al Khushaybi": "ELQ019",
            "Al Khuznah": "GIZ045",
            "Al Kihayfiyah": "HAS021",
            "Al Lahabah": "HBT003",
            "Al Lahien": "MED018",
            "Al Lith": "JED006",
            "Al Madaya": "GIZ046",
            "Al Madeed": "AHB060",
            "Al Madha": "AHB016",
            "Al Mahani": "TIF005",
            "Al Mahdam": "TIF006",
            "Al Majmaah": "MJH001",
            "Al Makhwah": "ABT012",
            "Al Malqa": "ELQ020",
            "Al Maqnah": "TUU007",
            "Al Maqrah": "MAC007",
            "Al Marameh": "ULH004",
            "Al Massamah": "JED007",
            "Al Mataein": "GIZ047",
            "Al Matrafiyah": "HAS022",
            "Al Mawarid": "JED008",
            "Al Mayyah": "HAS023",
            "Al Mejammah": "GIZ048",
            "Al Mejannah": "GIZ049",
            "Al Meqarqam": "GIZ050",
            "Al Mindassah": "MED019",
            "Al Mishaliah": "EAM005",
            "Al Mishilasah": "GIZ051",
            "Al Mithnab": "ELQ021",
            "Al Mogali": "GIZ052",
            "Al Mothalath": "YNB009",
            "Al Muaeliah": "YNB010",
            "Al Mubarak": "MAC008",
            "Al Mubarakah": "GIZ053",
            "Al Mubarraz": "HOF003",
            "Al Mudayyih": "HAS024",
            "Al Mufrihat": "MED020",
            "Al Mulaylih": "MED021",
            "Al Muqarah": "YNB011",
            "Al Muraba'A": "YNB012",
            "Al Musayjid": "MED022",
            "Al Mushaytiyah": "HAS025",
            "Al Mustajiddah": "HAS026",
            "Al Muwaileh": "EJH002",
            "Al Muwassam": "GIZ054",
            "Al Muwayh": "TIF007",
            "Al Muzahimiyah": "RUH013",
            "Al Nabah": "YNB013",
            "Al Nagaf": "YNB014",
            "Al Najameiah": "GIZ055",
            "Al Namas": "AHB017",
            "Al Nasfah": "AJF006",
            "Al Nashifah": "ULH005",
            "Al Nkheel": "MED023",
            "Al Nuaibea'A": "JED009",
            "Al Omaq": "MED024",
            "Al Ous": "AHB018",
            "Al Oyun": "HOF004",
            "Al Petra": "ELQ022",
            "Al Qa'": "ABT015",
            "Al Qadeimah": "JED010",
            "Al Qahma": "GIZ056",
            "Al Qaid": "HAS027",
            "Al Qaisumah": "AQI001",
            "Al Qaiyah": "ELQ059",
            "Al Qalibah": "TUU010",
            "Al Qanboor": "GIZ057",
            "Al Qaraa": "ELQ023",
            "Al Qarah": "HOF005",
            "Al Qasab": "DWD006",
            "Al Qatif": "DMM008",
            "Al Qirah": "WAE008",
            "Al Qouz": "ABT016",
            "Al Qrash": "YNB015",
            "Al Quamah": "TIF008",
            "Al Qulayyib": "QJB002",
            "Al Qunfudhah": "ABT058",
            "Al Qurainah": "RUH016",
            "Al Qurayb": "GIZ058",
            "Al Qurayn": "ELQ060",
            "Al Qurayyah": "HOF022",
            "Al Qurayyat": "URY",
            "Al Quwaiiyah": "DWD007",
            "Al Quwarah": "ELQ024",
            "Al Radha": "GIZ059",
            "Al Rafaya": "HAS028",
            "Al Ramdhah": "MED025",
            "Al Rathaya": "MED026",
            "Al Reeth": "GIZ060",
            "Al Rehab": "MED027",
            "Al Rokobah": "GIZ061",
            "Al Salhaniyah": "MED028",
            "Al Sarhan": "AHB019",
            "Al Sawarima": "GIZ062",
            "Al Sedr": "MED049",
            "Al Selselah": "MED029",
            "Al Ser": "GIZ063",
            "Al Sewideiah": "GIZ064",
            "Al Shaaf": "AHB020",
            "Al Shaafoleiah": "GIZ065",
            "Al Shabain": "AHB021",
            "Al Shabhah": "YNB016",
            "Al Shabitah": "GIZ066",
            "Al Shadakh": "YNB017",
            "Al Sharjah": "YNB018",
            "Al Shegrah": "MED030",
            "Al Shfeah": "MED050",
            "Al Shlayil": "MED031",
            "Al Shuqaiq": "GIZ067",
            "Al Sir": "TIF009",
            "Al Subaykhah": "AHB022",
            "Al Sufah": "EAM006",
            "Al Sulaimi": "HAS029",
            "Al Tarafayh Al Sharqiyah": "ELQ025",
            "Al Thamad": "MED032",
            "Al Tiraq": "ELQ026",
            "Al Tuwal": "GIZ068",
            "Al Udayliyah": "HOF006",
            "Al Uferiah": "ABT018",
            "Al Ula": "ULH001",
            "Al Umran": "HOF007",
            "Al Uwayqilah": "RAE001",
            "Al Uyaynah": "RUH040",
            "Al Uzaym": "HAS030",
            "Al Wadeen": "AHB023",
            "Al Wahla": "GIZ069",
            "Al Wajh": "EJH001",
            "Al Wannan": "QJB003",
            "Al Wasah": "HAS031",
            "Al Wozeyh": "HOF008",
            "Al Wuhait": "TIF010",
            "Al Zabira": "HAS032",
            "Al-Ahmar": "YNB019",
            "Al-Asamlah Alkobra": "GIZ072",
            "Al-Asfan": "AJF008",
            "Al-Fuwayliq": "ELQ012",
            "Al-Jouf": "GIZ124",
            "Al-Uyaynah": "QJB017",
            "Alabadilah": "GIZ070",
            "Alaliya": "GIZ071",
            "Albarek": "ABT020",
            "Alduwaid": "AJF009",
            "Aleumud": "TUU011",
            "Alfaraaien": "AHB024",
            "Alfareeq": "ABT021",
            "Alfera": "YNB020",
            "Algayed": "GIZ073",
            "Alhrateem": "ABT022",
            "Alhumaid": "ABT023",
            "Alhumaimah": "MAC009",
            "Aljfarah": "RUH019",
            "Alkhdra": "GIZ074",
            "Alkhuraybah": "TUU012",
            "Alkwifriah": "HOF023",
            "Allaghamees": "ABT024",
            "Almajaridah": "AHB025",
            "Almajdirah": "GIZ125",
            "Almandaq": "ABT025",
            "Almansoria": "GIZ075",
            "Almihdar": "HOF024",
            "Almnadh": "TIF011",
            "Almorshediah": "MAC010",
            "Almu'Tadil": "MED033",
            "Almuzaylif": "ABT014",
            "Almuzayri": "RUH020",
            "Alqalh": "JED011",
            "Alqarei": "ABT026",
            "Alquaba": "ABT027",
            "Alsadliyah": "GIZ076",
            "Alsadyah": "JED013",
            "Alsalhiya": "RUH021",
            "Alshuqayri": "GIZ077",
            "Alshwaaq": "ABT028",
            "Alsilaa": "GIZ078",
            "Alsourah": "EJH003",
            "Alwasqah": "ABT029",
            "Alwastah": "YNB021",
            "Alyutamah": "MED034",
            "Amaaer Ben Sanaa": "HAS033",
            "Amaq": "ABT030",
            "An Nabhaniyah": "ELQ027",
            "An Nabk Abu Qasr": "AJF010",
            "An Nawwariyyah": "MAC011",
            "Anak": "DMM014",
            "Ar Rafi'Ah": "AJF011",
            "Ar Rafiah": "HBT004",
            "Ar Rass": "ELQ028",
            "Ar Rawdah": "HAS034",
            "Ar Rayis": "YNB022",
            "Ar Rayn": "DWD009",
            "Ar Rishawiyah": "HAS076",
            "Ar Ruqi": "HBT005",
            "Ar Ruwaidhah": "DWD010",
            "Arab": "AHB026",
            "Arar": "RAE",
            "Ardah": "GIZ079",
            "Arja": "DWD011",
            "Arya": "TIF012",
            "As Saban": "HAS035",
            "As Sadawi": "HBT006",
            "As Saddain": "TIF013",
            "As Saddain Balharith": "TIF014",
            "As Saffaniyah": "HBT022",
            "As Safra": "HAS036",
            "As Sail Al Kabeer": "TIF015",
            "As Sarrar": "QJB004",
            "As Sayl As Saghir": "TIF016",
            "As Shwimes": "HAS037",
            "As Siayyirah": "HAS038",
            "As Sihaf": "QJB005",
            "As Silayyil": "HAS039",
            "As Sirr": "GIZ080",
            "As Suairah": "QJB006",
            "As Sufayri": "HBT007",
            "As Sufun": "HAS040",
            "As Sulayyil": "SLF001",
            "As Sulubiayh": "ELQ029",
            "As Sunayna": "HAS041",
            "As Suwadirah": "MED035",
            "Asbtar": "HAS042",
            "Asfan": "JED014",
            "Ash Shaalaniyah": "HAS043",
            "Ash Shafa": "TIF017",
            "Ash Shamiyah": "MAC012",
            "Ash Shamli": "HAS044",
            "Ash Shamlul": "HBT008",
            "Ash Sharai": "MAC023",
            "Ash Shihiyah": "HBT009",
            "Ash Shihyah": "ELQ030",
            "Ash Shimasiyah": "ELQ031",
            "Ash Shinan": "HAS045",
            "Ash Shubah": "HBT010",
            "Ash Shubaykiyah": "ELQ032",
            "Ash Shumaysi": "MAC013",
            "Ash Shuqayq": "HAS046",
            "Ash-Shamiyah": "HBT011",
            "Ashayrah": "TIF018",
            "Asuwayq": "YNB023",
            "Asuwayriqyah": "MED036",
            "At Tawdihiyah": "RUH025",
            "Atawleh": "ABT031",
            "Ateef": "TIF019",
            "Ath Thamiriyah": "ELQ033",
            "Ath Thybiyah": "HBT012",
            "Awirah": "ABT032",
            "Ayn Ibn Fuhayd": "ELQ034",
            "Az Zafir": "ABT033",
            "Az Zalal": "MAC014",
            "Az Zemah": "MAC015",
            "Az Zughayn": "QJB007",
            "Az Zulfi": "ZUL001",
            "Bada": "EJH004",
            "Badaa'I Alsadiah": "HAS047",
            "Badr": "YNB024",
            "Badr Al Janoub": "EAM007",
            "Bahr Abu Sukaynah": "AHB027",
            "Bahrah": "JED015",
            "Baish": "GIZ081",
            "Baish Alolia": "GIZ082",
            "Baljurashi": "ABT034",
            "Bani Amr": "AHB028",
            "Bani Hasan": "ABT035",
            "Bani Horairah": "ABT036",
            "Bani Kabir": "ABT037",
            "Bani Mouhamad": "ABT038",
            "Bani Saad": "TIF020",
            "Baqaa": "HAS048",
            "Bariq": "AHB029",
            "Bashout": "AHB030",
            "Bayda Natheel": "HAS049",
            "Beda'A Ben Khalaf": "HAS050",
            "Bidah Valley": "ABT039",
            "Bilad Biny Suhaim": "ABT040",
            "Billasmar": "AHB031",
            "Bir Ibn Hirmas": "TUU015",
            "Bisha": "BHH",
            "Blhamr": "AHB032",
            "Bny Yazed": "JED016",
            "Buqayq": "DMM020",
            "Buraydah": "ELQ",
            "Burudan": "DWD012",
            "Da'A": "ULH006",
            "Dabir": "GIZ083",
            "Dahaban": "JED017",
            "Damad": "GIZ084",
            "Dammam": "DMM",
            "Dariyah": "ELQ036",
            "Dayhamah": "GIZ085",
            "Dayida": "ELQ037",
            "Deli Rashid": "ELQ038",
            "Dhahran": "DHA001",
            "Dhahran Al Janub": "AHB033",
            "Dhalm": "TIF021",
            "Dhubaya Jumah": "JED018",
            "Dhurma": "RUH027",
            "Doos": "ABT041",
            "Doqah": "ABT042",
            "Dremeha": "ELQ039",
            "Duba": "EJH005",
            "Dubay'Ah": "HAS051",
            "Duhknah": "ELQ040",
            "Dulayhan": "HAS052",
            "Dumah Al Jandal": "AJF012",
            "Economic City": "GIZ086",
            "Ein As Suwaine": "ELQ041",
            "Either": "GIZ087",
            "Enaker": "ABT043",
            "Fadhla": "ULH007",
            "Farasan": "GIZ088",
            "Fayd": "HAS053",
            "Faydat Athqab": "HAS054",
            "Faydat Ibn Suwaylim": "HAS055",
            "Fayfa": "GIZ089",
            "Feyadh Tabrjal": "AJF013",
            "Gayal": "TUU017",
            "Ghamrah": "HAS077",
            "Ghanwa": "QJB008",
            "Ghazaial": "TIF022",
            "Ghezlanh": "HAS056",
            "Ghizlan": "QJB018",
            "Ghomygah": "JED019",
            "Ghran": "JED020",
            "Ghtai": "URY004",
            "Gizan": "GIZ",
            "Habbes": "GIZ091",
            "Habil": "ABT044",
            "Hadaad Bani Malek": "TIF023",
            "Hadabah": "HAS057",
            "Hadban": "AJF015",
            "Hadda": "JED021",
            "Haddat Ash Sham": "MAC016",
            "Hafar Al Batin": "HBT",
            "Hafir Kishb": "TIF024",
            "Hafirat Nisah": "RUH058",
            "Hafr Al Atk": "RUH028",
            "Hail": "HAS",
            "Hajanbah": "GIZ092",
            "Hajar": "JED022",
            "Hajrah": "ABT045",
            "Hakimat Abu Arish": "GIZ093",
            "Hakimat Al Dagharir": "GIZ094",
            "Halaba": "AHB034",
            "Halat Ammar": "TUU018",
            "Halban": "DWD013",
            "Hali": "ABT046",
            "Hanidh": "QJB009",
            "Haql": "TUU019",
            "Haradh": "HOF009",
            "Harub": "GIZ095",
            "Hautat Sudair": "RUH030",
            "Hawiyah": "HOF010",
            "Hazem Aljalamid": "RAE002",
            "Hazwa": "RUH064",
            "Hedeb": "AJF017",
            "Hefar": "ABT047",
            "Helah": "AHB058",
            "Hibran": "HAS059",
            "Hijrat Fadila": "HOF011",
            "Hofuf": "HOF",
            "Howtat Bani Tamim": "RUH031",
            "Hubuna": "EAM008",
            "Hulayfa": "HAS060",
            "Huraymila": "RUH032",
            "Husnah": "MAC017",
            "Isharah": "ULH008",
            "Ithrah": "URY005",
            "Jalajil": "RUH033",
            "Jamajm": "AJF018",
            "Jamalah": "GIZ096",
            "Jarab": "ABT048",
            "Jash": "AHB035",
            "Jeddah": "JED",
            "Jilah": "RUH034",
            "Joraibah": "GIZ097",
            "Joribah": "GIZ098",
            "Juatha": "HOF013",
            "Jubail": "QJB",
            "Jubbah": "HAS061",
            "Judah": "DMM025",
            "Kaf": "URY006",
            "Keyad": "ABT049",
            "Khabt Saeed": "GIZ099",
            "Khafji": "HBT015",
            "Khaiber Al Janoub": "AHB036",
            "Khairan": "WAE009",
            "Khamis Harb": "ABT069",
            "Khamis Mushait": "KMX001",
            "Khamis Mutair": "AHB037",
            "Khathaam": "ABT050",
            "Khathirah": "GIZ100",
            "Khawarah": "GIZ101",
            "Khaybar": "MED039",
            "Khbash": "EAM009",
            "Khef Hussain": "YNB025",
            "Khulais": "JED024",
            "Khurais": "HOF014",
            "Khursaniyah": "QJB010",
            "King Abdullah Economic City": "JED025",
            "King Abdullah Housing": "GIZ102",
            "King Khalid Military City": "KMC001",
            "Layla": "WAE010",
            "Linah": "HBT016",
            "Madain Saleh": "ULH009",
            "Madrak": "GIZ103",
            "Madrakah": "MAC018",
            "Maghsheiah": "GIZ104",
            "Mahalah": "GIZ105",
            "Mahd Al Thahab": "MED040",
            "Makkah": "MAC",
            "Makshosh": "ABT051",
            "Malakan": "MAC020",
            "Malha": "GIZ106",
            "Malham": "RUH035",
            "Manshabah": "GIZ107",
            "Marabah": "GIZ108",
            "Marat": "DWD014",
            "Marj Allsoban": "HBT017",
            "Masader": "ULH010",
            "Masliyah": "GIZ109",
            "Mastorah": "JED026",
            "Mawqaq": "HAS062",
            "Maysaan": "TIF025",
            "Medina": "MED",
            "Meegowa": "AJF019",
            "Minwa": "URY007",
            "Mishalah": "HBT018",
            "Mishash Jurud": "ELQ042",
            "Mizhirah": "GIZ110",
            "Mogayra": "ULH011",
            "Morighan": "AHB038",
            "Mubhel": "ELQ043",
            "Mudarraj": "ELQ044",
            "Muhayil": "AHB039",
            "Muhayriqah": "DWD008",
            "Mulayjah": "QJB011",
            "Musaylah": "ABT052",
            "Nabat": "YNB026",
            "Nairyah": "QJB012",
            "Najran": "EAM",
            "Namerah": "ABT053",
            "Naylat": "HAS063",
            "Nebak": "QJB019",
            "New Ain Dar": "DMM030",
            "New Muwayh": "TIF026",
            "Nifi": "DWD015",
            "Nimran": "TIF027",
            "Nkheelan": "DWD016",
            "Old Ain Dar": "DMM031",
            "Ottoman Fortress": "JED027",
            "Qae Alshaqiq": "GIZ111",
            "Qaim Aldash": "GIZ112",
            "Qana": "AHB041",
            "Qaryat Al Ulya": "QJB013",
            "Qasr Ibn Ogail": "ELQ045",
            "Qbah": "ELQ046",
            "Qia": "TIF028",
            "Qilwah": "ABT054",
            "Qina": "HAS064",
            "Qlayyb Khedr": "URY008",
            "Qudaid": "JED028",
            "Qusaiba": "ELQ047",
            "Rabigh": "JED029",
            "Radifah": "AJF021",
            "Radwan": "TIF029",
            "Rafaya Al Jamsh": "DWD017",
            "Rafha": "RAH",
            "Rahat": "MAC021",
            "Rahib": "TUU020",
            "Ranyah": "TIF036",
            "Ras Al Khair": "QJB014",
            "Ras Tanura": "DMM46",
            "Raudat Sudair": "RUH042",
            "Rawd Ibn Hadi": "HAS065",
            "Rawdat Habbas": "HBT019",
            "Riaa Albekr": "HAS066",
            "Rijal Alma": "AHB042",
            "Riyadh": "RUH",
            "Riyadh Al Khabra": "ELQ048",
            "Rojal": "AHB043",
            "Rumah": "RUH044",
            "Ruwayghib": "RUH045",
            "Sa'Ad": "RUH059",
            "Saabar": "JED030",
            "Sabbath Shumran": "AHB044",
            "Sabt Al Alayah": "BHH003",
            "Sabt Aljarah": "ABT055",
            "Sabya": "GIZ113",
            "Safinah": "MED043",
            "Safwa": "DMM035",
            "Saihat": "DMM036",
            "Sajir": "DWD018",
            "Sakaka": "AJF022",
            "Salamh Al Darraj": "GIZ114",
            "Salbukh": "RUH055",
            "Salm Alzwaher": "ABT056",
            "Salwa": "HOF025",
            "Samakh": "BHH004",
            "Samhah": "MED044",
            "Sammed": "MAC022",
            "Samrat Al Jed": "GIZ115",
            "Samtah": "GIZ116",
            "Saq": "ELQ049",
            "Sarat Abidah": "AHB047",
            "Sayaa": "JED031",
            "Sayadah": "TIF030",
            "Sayyabah": "GIZ117",
            "Seddeqah": "GIZ118",
            "Shaghab": "TUU021",
            "Shaqra": "DWD019",
            "Shari": "ELQ050",
            "Sharma": "EJH006",
            "Sharorah": "SHW",
            "Shawyah": "RUH065",
            "Shaybah": "HOF026",
            "Shedgum": "HOF015",
            "Shigry": "TUU023",
            "Shoaiba": "JED032",
            "Shoqsan": "TIF031",
            "Shumran": "AHB048",
            "Shuwaq": "TUU024",
            "Starah": "WAE012",
            "Su'Aydan": "HAS067",
            "Sude'A": "URY009",
            "Suhailah": "DWD020",
            "Sulailah Juhainah": "MED045",
            "Sumairaa": "HAS068",
            "Suwayr": "AJF024",
            "Tabah": "HAS069",
            "Tabalah": "BHH005",
            "Tabrjal": "AJF025",
            "Tabuk": "TUU",
            "Taif": "TIF",
            "Takhayil": "HAS070",
            "Tala'At Naza": "YNB027",
            "Tallan": "GIZ119",
            "Tanajib": "HBT023",
            "Tanomah": "AHB050",
            "Tanumah": "ELQ051",
            "Tara'Ah": "YNB028",
            "Tareeb": "AHB051",
            "Tarout": "DMM040",
            "Tathleeth": "BHH006",
            "Tayma": "TUU026",
            "Tendaha": "AHB053",
            "Thadiq": "RUH048",
            "Thaj": "QJB015",
            "Thar": "EAM011",
            "Tharmda": "DWD021",
            "Thloth Al Mandhar": "AHB054",
            "Thuwal": "JED033",
            "Tirah": "TIF033",
            "Trubah": "HAS071",
            "Tuhayyi": "DWD022",
            "Tumair": "RUH051",
            "Turaif": "TUI",
            "Turbah": "TIF034",
            "Ubayrah": "HAS072",
            "Udhailiyah": "HOF016",
            "Uglat Asugour": "ELQ052",
            "Um Alerrad": "DMM042",
            "Um Aljerem": "JED034",
            "Um Ash Shifallah": "HBT021",
            "Um Saad": "GIZ120",
            "Umluj": "EJH007",
            "Umm Al Jamajm": "ELQ053",
            "Umm Aldoom": "TIF035",
            "Umm Rujoum": "RUH052",
            "Unayzah": "UZH001",
            "Uqlat Ibn Dani": "HAS073",
            "Uqlat Ibn Twalah": "HAS074",
            "Urayarah": "DMM043",
            "Urayja": "HAS075",
            "Ushaiqer": "DWD023",
            "Ushairat Sudair": "RUH054",
            "Utayiq": "QJB016",
            "Uthal": "ELQ054",
            "Uthmaniyah": "HOF017",
            "Uyun Al Jawa": "ELQ055",
            "Waad Al Shaamaal": "AJF026",
            "Waaer": "BHH007",
            "Wadi Al Dawasir": "WAE",
            "Wadi Al Fora'A": "MED046",
            "Wadi Al Hayat": "GIZ121",
            "Wadi Amoud": "GIZ122",
            "Wadi Badhan": "MED047",
            "Wadi Ibn Hashbal": "AHB056",
            "Wadi Shora": "ABT057",
            "Waset": "WAE014",
            "Wushai": "RUH062",
            "Yaara": "AHB057",
            "Yabreen": "HOF018",
            "Yadamah": "EAM012",
            "Yalamlam": "JED035",
            "Yanbu": "YNB",
            "Yanbu Al Nakhal": "YNB031",
            "Zalom": "AJF027",
            "Zamzam": "GIZ123"
        }
    },
    # 'AE': {
    #     'country_code': 'AE',
    #     'city_codes': {
    #         'Ajman': 'QAJ',
    #         'Fujairah': 'FJR',
    #         'Al Ain': 'AAN',
    #         'Ras al Khaimah': 'RKT',
    #         'Umm Al Quwain': 'QIW',
    #         'Al Taweelah ': 'AUH0021',
    #         'Khor Fakkan': 'SHJ0005',
    #         'Zayed Military City': 'AUH0052',
    #         'Al Adla': 'AUH0002',
    #         "Al 'Asheesh": 'AUH0005',
    #         'Al Fathiya': 'AUH0009',
    #         "Al Sila'a": 'AUH0020',
    #         'Barakah': 'AUH0030',
    #         'Al Hamra': 'AUH0010',
    #         'Ruwais': 'AUH0044',
    #         'Ghayathi': 'AUH0033',
    #         'Al Mirfa': 'AUH0014',
    #         'Madinat Zayed': 'AUH0039',
    #         'Bu Hasa': 'AUH0031',
    #         'Liwa': 'AUH0038',
    #         'Arada': 'AUH0028',
    #         'Um Al Hosn Oasis': 'AUH0049',
    #         'Taraq': 'AUH0047',
    #         'Kayyam': 'AUH0037',
    #         'Asab': 'AUH0029',
    #         'Alyhyali': 'AUH0027',
    #         'Mezairaa': 'AUH0041',
    #         'Sabkhah': 'AUH0045',
    #         'Al Tharwania': 'AUH0022',
    #         'Al Nashash': 'AUH0015',
    #         'Al Yabbana': 'AUH0024',
    #         'Dahin': 'AUH0032',
    #         'Jarrah': 'AUH0035',
    #         'Wedhail': 'AUH0050',
    #         'Wothain': 'AUH0051',
    #         'Al Yarya': 'AUH0026',
    #         'Al Khis': 'AUH0013',
    #         'Hamim': 'AUH0034',
    #         'Jereirah': 'AUH0036',
    #         'Tarif': 'AUH0048',
    #         "Al Quo'a Town": 'AUH0016',
    #         'Al Wagan': 'AUH0023',
    #         'Al Araad': 'AUH0004',
    #         'Abu Krayyah': 'AUH0001',
    #         'Al Dhahra': 'AUH0007',
    #         'Remah': 'AUH0043',
    #         'Al Khaznah': 'AUH0012',
    #         'Al Yahar': 'AUH0025',
    #         'Al Saad': 'AUH0017',
    #         'Al Bada': 'AUH0006',
    #         'Masaken': 'AUH0040',
    #         'Al Hayer': 'AUH0011',
    #         'Al Shuwaib': 'AUH0019',
    #         'Al Faqa': 'AUH0008',
    #         'Nahil': 'AUH0042',
    #         'Sweihan': 'AUH0046',
    #         'Al Ajban': 'AUH0003',
    #         'Al Samha': 'AUH0018',
    #         'Nazwa': 'SHJ0008',
    #         'Al Madam': 'SHJ0003',
    #         'Maleha': 'SHJ0006',
    #         'Al Dhaid': 'SHJ0001',
    #         'Nahwa': 'SHJ0007',
    #         'Al Zubair': 'SHJ0004',
    #         'Al Hamriya': 'SHJ0002',
    #         'Ghub': 'FJR0013',
    #         'Dibba Al Fujairah': 'FJR0012',
    #         'Dhadna': 'FJR0011',
    #         'Al Aqah': 'FJR0002',
    #         'Sharm': 'FJR0016',
    #         'Al Bidya': 'FJR0003',
    #         'Zubara': 'FJR0019',
    #         'Al Halah': 'FJR0005',
    #         'Al Uyaynah': 'FJR0009',
    #         'Abadilah': 'FJR0001',
    #         'Tayybah': 'FJR0017',
    #         'Asimah': 'FJR0010',
    #         'Al Khulaybiyah': 'FJR0007',
    #         'Mirbah': 'FJR0015',
    #         'Al Qurayya': 'FJR0008',
    #         'Al Bithnah': 'FJR0004',
    #         'Al Hayl': 'FJR0006',
    #         'Harrah': 'FJR0014',
    #         'Wadi Al Helo': 'FJR0018',
    #         'Al Qawr': 'RKT0006',
    #         'Munay': 'RKT0015',
    #         'Sahaynah': 'RKT0017',
    #         'As Simsimsaniyyah': 'RKT0007',
    #         'Huwaylat': 'RKT0011',
    #         'Fashrah': 'RKT0009',
    #         'Faha': 'RKT0008',
    #         'Rafaq': 'RKT0016',
    #         'Al Husayn': 'RKT0002',
    #         'Shawka': 'RKT0019',
    #         'Al Khari': 'RKT0005',
    #         'Maghribiyah': 'RKT0013',
    #         'Masafi': 'RKT0014',
    #         'Adhen Village': 'RKT0001',
    #         'Ghalilah': 'RKT0010',
    #         "Sha'am": 'RKT0018',
    #         'Al Jeer': 'RKT0004',
    #         'Wadi Shaam': 'RKT0020',
    #         'Al Jazirah Al Hamra': 'RKT0003',
    #         'Khatt': 'RKT0012',
    #         'Al Ail': 'QIW0001',
    #         'Al Rafaah': 'QIW0002',
    #         'Falaj Al Mualla': 'QIW0004',
    #         'Al Rashidiya': 'QIW0003',
    #         'Sayh Mudayrah': 'QAJ0002',
    #         'Al Manama': 'QAJ0001',
    #         'Al Lisaili': 'DXB0002',
    #         'Murqquab': 'DXB0006',
    #         'Margham': 'DXB0005',
    #         'Lahbab': 'DXB0004',
    #         'Al Awir': 'DXB0001',
    #         'Hatta': 'DXB0003',
    #         'Abu Dhabi': 'AUH',
    #         'Dubai': 'DXB',
    #         'Sharjah': 'SHJ'
    #     }
    # },
}


class CityCodeNotFound(Exception):
    pass


def get_city_code(country, cities):
    if country in CITY_CODES:
        for city in cities:
            city_code = CITY_CODES[country]['city_codes'].get(city.strip().title())
            if city_code:
                return city_code
    raise CityCodeNotFound()


def get_country_code(country):
    return CITY_CODES[country]['country_code']
