CITY_CODES = {
    'Abu Areish': 'Abu Arish',
    'Ahad Masarha': 'Ahad Al Masarhah',
    'Ohod Rafeedah': 'Ahad Rafidah',
    'Ahad Rufaidah': 'Ahad Rafidah',
    'Al Aqiq': 'Aqiq',
    'Badaye': 'Badaya',
    'Bader': 'Badr',
    'Bisha': 'Bishah',
    'Dawadmi': 'Duwadimi',
    'Dhahran Al Janoob': 'Dhahran Aljanoub',
    'Dharma': 'Dhurma',
    'Domat Al Jandal': 'Dawmat Al Jandal',
    'Duba': 'Dhuba',
    'Jazan': 'Gizan',
    'Hafer Al Batin': 'Hafar Al Baten',
    'Haqil': 'Haql',
    'Hinakeya': 'Hanakiyah',
    'Hofuf': 'Hufuf',
    'Hotat Sudair': 'Hawtat Sudair',
    'Huraymala': 'Huraymila',
    'Khaibar': 'Khayber',
    'Khamis Mushait': 'Khamis Mushayt',
    'Khlais': 'Khulais',
    'Khubar': 'Khobar',
    'Khurma': 'Khurmah',
    'Laith': 'Lith',
    'Majardah': 'Majarda',
    'Majma': 'Majmaah',
    'Mandak': 'Mandaq',
    'Mhayel': 'Muhayil',
    'Midinhab': 'Midhnab',
    'Mikhwa': 'Mukhwah',
    'Nairyah': 'Nairiyah',
    'Qaryah Al Oliya': 'Qarya Ulya',
    'Qaryah Al Ulya': 'Qarya Ulya',
    'Qunfudah': 'Qunfudhah',
    'Qurayat': 'Qurayyat',
    'Rania': 'Ranyah',
    'Ras Tanura': 'Ras Tannurah',
    "Rejal Alma'A": 'Rijal Alma',
    'Remah': 'Rumah',
    'Sabt El Alaya': 'Sabt Al Alaya',
    'Sapt Al Alaya': 'Sabt Al Alaya',
    'Sapt El Alaya': 'Sabt Al Alaya',
    'Sakaka': 'Skakah',
    'Sarat Obeida': 'Sarat Abida',
    'Seihat': 'Sayhat',
    'Sulaiyl': 'Sulayyil',
    'Tabrjal': 'Tabarjal',
    'Tanuma': 'Tanumah',
    'Tayma': 'Taima',
    'Turaif': 'Turayf',
    'Turba': 'Turbah',
    'Uqlat Al Suqur': 'Uqlat As Suqur',
    'Wadi El Dwaser': 'Wadi Al Dawasir',
    'Wadi Al-Dawasir': 'Wadi Al Dawasir',
    'Wajeh': 'Wajh',
    'Al Wajh': 'Wajh',
    'Yanbu Al Baher': 'Yanbu',
    'Yanbu Industrial City': 'Yanbu',
}
