SA = {
    'Abha': 'Abha',
    'Abqaiq': 'Abqaiq',
    'Abu areish': 'ABU ARISH',
    'Abu hadriyah': 'ABU HADRIYAH',
    'Afif': 'Afif',
    'Aflaj': 'Aflaj',
    'Ahad masarha': 'AHAD MASARAH',
    'Ahad rufaidah': 'AHAD ROFAIDAH',
    'Ain dar': 'Ain Dar',
    'Ajfar': 'AJFAR',
    'Ajyad': 'AJYAD',
    'Al anbariya': 'AL ANBARIYA',
    'Al aqiq': 'AQEEQ',
    'Al arisa': 'AL ARISA',
    'Al awaly': 'AL AWALY',
    'Al ayss': 'AL AYSS',
    'Al baha': 'Al Baha',
    'Al bahar': 'AL BAHAR',
    'Al bakar': 'AL BAKAR',
    'Al bashair': 'AL BASHAIR',
    'Al bukayriyah': 'BUKAYRIA',
    'Al busaita': 'AL BUSAITA',
    'Al dalemya': 'DALEMIYA',
    'Al faghir': 'AL FAGHIR',
    'Al gazaz al balad': 'AL GAZAZ AL BALAD',
    'Al gewaizah': 'AL GEWAIZAH',
    'Al ghazah': 'AL GHAZAH',
    'Al goz': 'AL GOZ',
    'Al haet': 'AL HAET',
    'Al hajoun': 'AL HAJOUN',
    'Al hassa': 'AL HASA',
    'Al hurra al sharqya': 'AL HURRA AL SHARQYA',
    'Al jubail industrial': 'JUBAIL',
    'Al juhaima': 'AL JUHAIMA',
    'Al khurmah': 'KHURMA',
    'Al lith town': 'AL LITH TOWN',
    'Al mahd': 'Al Mahd',
    'Al majardah': 'MAJARDEH',
    "Al majma'ah": 'MAJMAAH',
    'Al mandaq': 'AL MANDAQ',
    'Al masfalah': 'AL MASFALAH',
    'Al mauta': 'AL MAUTA',
    'Al mawya': 'AL MAWYA',
    'Al moya': 'AL MOYAN',
    'Al muzahmeya': 'MUZAMMIA',
    'Al nabhanya': 'AL NABHANYA',
    'Al namass': 'AL NAMASS',
    'Al naqee': 'AL NAQEE',
    'Al otaibya': 'AL OTAIBYA',
    'Al oyoun': 'AL OYOUN',
    'Al quaara': 'AL QUAARA',
    'Al qunfuda': 'QUNFUDAH',
    'Al quwayiyah': 'QUWAYIAH',
    'Al rafaye': 'AL RAFAYE',
    'Al rain': 'AL RAIN',
    'Al safah': 'SAFA',
    'Al sayel al akbar': 'AL SAYEL AL AKBAR',
    'Al sharaa': 'AL SHARAA',
    'Al sharafiya': 'AL SHARAFIYA',
    'Al shuhada': 'AL SHUHADA',
    'Al suheimi': 'AL SUHEIMI',
    'Al ula': 'AL OLA',
    'Al zaher': 'AL ZAHER',
    'Al zulfi': 'ZILFI',
    'Alghat': 'AL GHAT',
    'Alhada': 'HADA',
    'All ministries': 'ALL MINISTRIES',
    'Alrass': 'AL RASS',
    'Altaif': 'TAIF',
    'Anak': 'ANAQ',
    'Aradah': 'ARADAH',
    'Arar': 'Arar',
    'Artawiah': 'Artawiah',
    'As suat': 'AS SUAT',
    'Assiyah': 'AL ASIYAH',
    'Atawleh': 'AL ATAWILAH',
    'Ayoon al jawa': 'AYOON AL JAWA',
    'Badaya': 'BADAYAH',
    'Badaye': 'BADAYAH',
    'Bader': 'BADR',
    'Baeish': 'BAEISH',
    'Bagadia': 'BAGADIA',
    'Baha': 'Baha',
    'Bahara': 'BAHRA',
    'Ballasmar': 'BALLASMAR',
    'Bani ammr': 'BANI AMMR',
    "Baqa'a": 'BAQAA',
    'Barb': 'BARB',
    'Bareq': 'Bareq',
    'Batha border': 'BATHA BORDER',
    'Biljurashi': 'BALJURSHI',
    'Bish': 'BEISH',
    'Bisha': 'Bisha',
    'Brazan': 'BRAZAN',
    'Buraidah': 'Buraidah',
    'Buraydah': 'BURAIDAH',
    'Damad': 'Damad',
    'Dammam': 'Dammam',
    'Darb': 'Darb',
    'Dawadmi': 'Dawadmi',
    'Dhabab': 'DHABAB',
    'Dhahran': 'Dhahran',
    'Dhahran al janoob': 'DHAHRAN AL JANOUB',
    'Dhalm': 'DHULUM',
    'Dharma': 'DURMA',
    'Dhobbat': 'DHOBBAT',
    'Dhukna': 'DHUKNA',
    'Dhurma': 'DURMA',
    'Dilam': 'DILAM',
    'Domat al jandal': 'DAWMAT AL JANDAL',
    'Duba': 'Duba',
    'Durya': 'DURYA',
    'Eskan': 'ESKAN',
    'Fawara': 'FAWARA',
    'Gassim': 'GASSIM',
    'Gella': 'GELLA',
    'Ghazalah': 'AL GHAZALAH',
    'Gizan': 'Gizan',
    'Habona': 'HABUNA',
    'Hafer al batin': 'HAFAR AL BATIN',
    'Hail': 'Hail',
    'Halat ammar': 'Halat Ammar',
    'Haqil': 'HAQL',
    'Harad': 'HARADH',
    'Hareeq': 'AL HAREEQ',
    'Harjah': 'AL HARJAH',
    'Haweyah': 'AL SUITEN AL HAWYA',
    'Hawtat bani tamim': 'HAWDAT TAMIM',
    'Hayet': 'HAYET',
    'Hayir': 'HAYIR',
    'Helban': 'HELBAN',
    'Hijaz': 'HIJAZ',
    'Hijrat laban': 'HIJRAT LABAN',
    'Hinakeya': 'HANAKIYAH',
    'Hiteem': 'HITEEM',
    'Hofuf': 'Hofuf',
    'Hota bin tamim': 'HOTA BIN TAMIM',
    'Hota sudhair': 'HOTA SUDHAIR',
    'Hotat sudair': 'HAWDAT SUDAIR',
    'Huraymala': 'HURAIMALA',
    'Imam university': 'IMAM UNIVERSITY',
    'Itayigah': 'ITAYIGAH',
    'Jabal al noor': 'JABAL AL NOOR',
    'Jafar': 'Jafar',
    'Jalajel': 'JALAJIL',
    'Jarda': 'JARDA',
    'Jareer': 'JAREER',
    'Jeddah': 'Jeddah',
    'Jouf': 'AL JOUF',
    'Jubail': 'Jubail',
    'Jubbah': 'JUBBAH',
    'Juhaimia': 'JUHAIMIA',
    'Jummum': 'AL JUMUM',
    'Jumum': 'JAMJOOM',
    'Kafa': 'KAFA',
    'Khabra': 'KHABRA',
    'Khafji': 'Khafji',
    'Khaibar': 'Khaibar',
    'Khalidya': 'KHALIDYA',
    'Khamis mushait': 'KHAMIS MUSHAYAT',
    'Kharj': 'AL KHARJ',
    'Khazzan': 'KHAZZAN',
    'Khobar': 'AL KHOBAR',
    'Khottah': 'KHUTTA',
    'Khubaib': 'KHUBAIB',
    'Khurais': 'KHURAIS',
    'Khurma': 'Khurma',
    'Laith': 'AL LITH',
    'Madinah': 'MEDINA',
    'Madinat yanbu al siniaya': 'YANBU',
    'Majarda': 'MAJARDEH',
    'Majma': 'MAJMAAH',
    'Makkah': 'Makkah',
    'Mandak': 'MANDAQ',
    'Manfouah': 'MANFOUAH',
    'Manfouha': 'MANFOUHA',
    'Mather': 'MATHER',
    'Mawqeq': 'MAWQEQ',
    'Mazrueya': 'MAZRUEYA',
    'Mecca': 'MAKKAH',
    'Megaibrah': 'MEGAIBRAH',
    'Midinhab': 'MIDHNAB',
    'Mikhwa': 'AL MIKHWA',
    'Mnefah': 'MANIFA',
    'Mogharazat': 'MOGHARAZAT',
    'Mohayel aseer': 'MAHAYIL ASEER',
    'Moqaq': 'Moqaq',
    'Mubaraz': 'AL MUBARRAZ',
    'Mubarraz': 'MUBARRAZ',
    'Munakhah': 'MUNAKHAH',
    'Mutamarat': 'MUTAMARAT',
    'Muthaleif': 'AL MUTHEILIEF',
    'Muzahmiah': 'MUZAMMIA',
    'Muzneb': 'MIDHNAB',
    'Nabaniya': 'NABANIYA',
    'Nafa': 'NAFA',
    'Naim': 'NAIM',
    'Nairyah': 'NARIYA',
    'Najran': 'NEJRAN',
    'Nesriyah': 'NESRIYAH',
    'New shimaisy': 'NEW SHIMAISY',
    'Ohod al masarha': 'AHAD MASARAH',
    'Ohod rafeedah': 'AHAD ROFAIDAH',
    'Onaiza': 'UNAYZAH',
    'Oqlah al suqour': 'OQLAH AL SUQOUR',
    'Oshaiger': 'OSHAIGER',
    'Oula': 'AL OLA',
    'Oyoon': 'OYOON',
    'Qaryah al oliya': 'QARYAT AL OLAYA',
    'Qasab': 'AL QASAB',
    'Qassim': 'AL QASSIM',
    'Qatif': 'Qatif',
    'Qaysoomah': 'QAISUMAH',
    'Qilwah': 'Qilwah',
    'Quba': 'QUBA',
    'Qubba': 'QUBBA',
    'Qunfudah': 'Qunfudah',
    'Qurayat': 'GURAYAT',
    'Quwayiyah': 'QUWAYIAH',
    "Quwei'ieh": 'QUWAYIAH',
    'Rabigh': 'Rabigh',
    'Rafha': 'Rafha',
    'Rahima': 'RAHIMAH',
    'Rahwa al bar': 'RAHWA AL BAR',
    'Rania': 'Rania',
    'Ras tanura': 'Ras Tanura',
    "Rejal alma'a": 'REJAL ALMAA',
    'Remah': 'RUMAH',
    'Riyadh': 'Riyadh',
    'Riyadh al khabra': 'RIYADH ALKHBRA',
    'Rowada': 'ROWADA',
    'Rowaida': 'ROWAIDA',
    'Ruwaidah': 'RUWAIDAH',
    'Sabt el alaya': 'SABTALAIA',
    'Sabya': 'Sabya',
    'Saeed al akalabi': 'SAEED AL AKALABI',
    'Safanyah': 'SAFANIYAH',
    'Safra': 'SAFRA',
    'Safwa': 'Safwa',
    'Sahna': 'AL SAHNA',
    'Saihat': 'SAIHAT',
    'Sajir': 'Sajir',
    'Sakaka': 'SAKAKAH',
    'Salamah': 'SALAMAH',
    'Salwa': 'SALWA',
    'Samah': 'SAMAH',
    'Samashiya': 'SAMASHIYA',
    'Samtah': 'Samtah',
    'Sarar': 'SARAR',
    'Sarat obeida': 'SARAT ABIDAH',
    'Seihat': 'SIAHAT',
    'Shamali': 'SHAMALI',
    'Shamsan': 'SHAMSAN',
    'Shaqra': 'SHAHQRA',
    'Shari': 'SHARI',
    'Sharorah': 'SHARURAH',
    'Sharourah': 'SHARURAH',
    'Shinanh': 'AL SHANAN',
    'Shoaiba': 'Shoaiba',
    'Sitten': 'SITTEN',
    'Souq alahad': 'SOUQ ALAHAD',
    'Sulaiyl': 'SULAYYIL',
    'Sumaira': 'SUMEIRA',
    'Tabuk': 'Tabuk',
    'Taif': 'Taif',
    'Tandaha': 'TANDAHA',
    'Tanuma': 'Tanuma',
    'Tarut': 'TARUT ISLAND',
    'Tatleeth': 'THATLEETH',
    'Tawoon': 'TAWOON',
    'Tayma': 'TAYMAH',
    'Thadek': 'THADIQ',
    'Thadiq': 'Thadiq',
    'Thareeb': 'THAREEB',
    'Thumair': 'THOMAIR',
    'Thuqba': 'TOUGABAH',
    'Towal': 'THOWAL',
    'Turaif': 'Turaif',
    'Turbah al shamal': 'TURBAH AL SHAMAL',
    'Udhaliyah': 'UDILLIYAH',
    'Um al qura': 'UM AL QURA',
    'Um al sahek': 'UM AL SAHEK',
    'Umluj': 'UMLUJJ',
    'Unaizah': 'UNAYZAH',
    'Uqlat al suqur': 'UQLAQ AL SUGGUR',
    'Urabah quarter': 'URABAH QUARTER',
    'Uyun': 'UYENAH',
    'Wadeien': 'AL WADYAYN',
    'Wadi el dwaser': 'WADI AL DAWASIR',
    'Wadi hashbel': 'WADI HASHBEL',
    'Wajeh (al wajh)': 'AL WAJH',
    'Worood': 'WOROOD',
    'Yadma': 'AL YATMA',
    'Yanbu': 'Yanbu',
    'Yanbu al baher': 'YANBU',
    'Yanbu industrial city': 'YANBU',
    'Zawiyah': 'ZAWIYAH',
    'Zdihar': 'ZDIHAR',
    'Zulfi': 'ZILFI',
}

BAHRAIN = [
    "AALI", "ADARI", "ADLIYA", "AL DUR", "AL EKER", "AL HAJAR", "AL HAMALAH", "AL MARKH",
    "AL SALMANIYAH", "AL-HIDD", "AMWAJ", "ASKAR", "AWALI", "BARBAR", "BUDAIYA", "DIPLOMATIC AREA", "DURT AL BAHRAIN",
    "HAMAD TOWN", "ISA TOWN", "JANABIYAH", "JANUSAN", "MAAMMER", "MANAMA", "MUHARRAQ", "QALALI", "RIFFA", "RIFFA VIEWS",
    "RLC", "SAAR", "SAKHIR", "SALMABAD", "SANABIS", "SANAD", "SEEF", "SITRA", "TASHAN", "ZALAQ",
]

EGYPT = [
    "10TH OF RAMADAN", "15TH OF MAY", "5TH SETTLEMENT", "6TH OF OCTOBER", "ABBARY", "ABDEEN", "ABOU HAMAD", "ABOU HOMUS",
    "ABOU KABIR", "ABOU KORKAS", "ABOU QIR", "ABOU SOUER", "ABOU SULTAN", "ABOU TESHT", "ABOU TIG", "ABU SIMBEL",
    "AGA", "AGOUZA", "AIN SHAMS", "AKHMEEM", "AL FATH", "AL HARAM", "AL TOOR", "ALEXANDRIA", "ALX PORT", "AMERYA FREE ZONE",
    "AMYRIA", "ANFOUSHI", "ASAFRA", "ASHMOUN", "ASSIUT", "ASWAN", "AWLAD SAKR", "AZARITA", "BAB EL SHAIRYA", "BACOS",
    "BADRASHEEN", "BALTEEM", "BANHA", "BANI MAZAR", "BASIOUN", "BEBA", "BEHERA", "BELA", "BELBEIS", "BELKAS", "BENI SUEF",
    "BERKET EL SABA", "BOLKY", "BORG EL ARAB", "BOULAQ", "BUSH", "CAIRO", "CAMP CHESAR", "CHATBY", "CLEOPATRA", "DAHAB",
    "DAKAHLIA", "DAMANHOUR", "DAMIETTA", "DAMIETTA PORT", "DAR SALAM", "DEKERNES", "DESHNA", "DESOUK", "DIR AL ABD",
    "DIR MAWAS", "DIRB NIGM", "DOKKI", "DOWN TOWN", "DYROUT", "EBSHWAY", "EDFOU", "EDKO", "EL ADWA", "EL AGAMY",
    "EL ALAMEEN", "EL ATTARIN", "EL BADARY", "EL BAGOUR", "EL BALANA", "EL BASATIN", "EL BOUSTAN", "EL DEKHELA",
    "EL DLINGAT", "EL FARAFRA", "EL FASHN", "EL FERDAN", "EL GAMAA", "EL GHANAIM", "EL GOMROK", "EL HAMOUL", "EL HEDAYA",
    "EL HOSANIA", "EL KHALIFA", "EL KHANKA", "EL KORIMAT", "EL KOSIA", "EL KOUSIER", "EL LABBAN", "EL LAHOUN", "EL MANDARA",
    "EL MARG", "EL MATARIA", "EL MAX", "EL MOSKI", "EL NAHDA", "EL NOBARIA", "EL NOZHA", "EL PHARANA", "EL REHAB",
    "EL REYAD", "EL SADAT", "EL SAHEL", "EL SALAM", "EL SANTA", "EL SHOUHDA", "EL SOUKHNA", "EL WADI EL GEDID", "EL WASTA",
    "EL WAYLI", "EL-SHEROUK CITY", "EMBABA", "ENSHAS", "ESNA", "ETAY EL BAROUD", "EYON MOUSA", "EZBIT EL-NAKHL", "FAISAL",
    "FAKOUS", "FARASKOUR", "FARSHOUT", "FAYED", "FAYOUM", "FLEMING", "GAMASA", "GAMEA IBRAHIM", "GANACLYS", "GARDEN CITY",
    "GHARBIA", "GIRGA", "GIZA", "GLYM", "HADARA", "HADAYEK", "HANNOVIL", "HAWAMDIA", "HELIOPOLIS", "HELWAN", "HURGHADA",
    "IBRAHIMIA", "ISMAILIA", "KABREET", "KAFR EL ARBAAEN", "KAFR EL BATIKH", "KAFR EL DAWAR", "KAFR EL SHEIKH", "KAFR EL ZAYAT",
    "KAFR GAZAR", "KAFR SAKR", "KAFR SHOKR", "KARMOUZ", "KASFARET", "KASR SAFA", "KASSASIN", "KLABSHA", "KOM EL DEKA",
    "KOM HAMADA", "KOUMUMBO", "LAURAN", "LUXOR", "MAADI", "MAAMOURA", "MAGHAGHA", "MAHALA EL KOBRA", "MALLAWY",
    "MANCHEYA", "MANFALOUT", "MANIAL", "MANKABAD", "MANSOURA", "MANZALA", "MARSA ALAM", "MARSA MATROUH", "MASHTOLSOK",
    "MATAREYA", "MATAY", "MATROUH", "MEET GHAMR", "MEET OQBA", "MENA EL BASAL", "MENA KAMH", "MENA NASR", "MENOUF",
    "MENYA", "METOBAS", "MIAMI", "MODEREYAT EL TAHRIR", "MOHANDESIN", "MOHARAM BEIK", "MOKATTAM", "MONOFIA", "MONSHAET NASSER",
    "MONTAZAH", "MOSTAFA KAMEL", "MOSTAFA PACHA", "NABAROH", "NAGA HAMDY", "NAQADA", "NASR CITY", "NEW CAIRO", "NORTH COAST",
    "NORTH SINAI", "NOUBA", "NUEBAA", "OBOUR CITY", "OLD CAIRO", "ORMAN", "PORT FOUAD", "PORT SAID", "PORT SAID, EL JAMIL",
    "QAHA", "QALIOUB", "QALIOUBIYA", "QANATER KHAIREYA", "QANATER SHARK", "QANTARA GHARB", "QEFT", "QELLIN", "QENA",
    "QOTOUR", "QOUS", "QUESNA", "RAFAH", "RAML STATION", "RAS EL-BAR", "RAS EL-SODA", "RAS EL-TIN", "RAS GHAREB",
    "RAS SIDR", "RASHID", "RED SEA", "ROD EL FARAG", "ROUSHDY", "SABA PACHA", "SADAT CITY", "SAFAGA", "SAFAR", "SAKKARA",
    "SALHIA GADIDA", "SAMALOUT", "SAMANOUD", "SAN STEFANO", "SANOURES", "SAQULTA", "SARWAT", "SAYEDA ZEINAB", "SEDFA",
    "SEMBILAWEEN", "SEMOUHA", "SHABAB MOSLEMIN", "SHALOUFA", "SHARABIA", "SHARKIA", "SHARM EL SHEIKH", "SHATANOUF",
    "SHEBIN EL KOUM", "SHERBEN", "SHOUBRA", "SHOUBRA EL KHEIMA", "SHUTS", "SIDI BISHR", "SIDI GABER", "SIDI SALEM",
    "SIOUF", "SOHAG", "SOTER", "SOUTH SINAI", "SPORTING", "ST CATHRIN", "STANLEY", "SUEZ", "TABA", "TAHTA", "TALA",
    "TALKHA", "TAMA", "TAMOH", "TANTA", "TEBEEN", "TEMA", "TOSHKA", "TOUKH", "VICTORIA", "WADI EL RAYAN", "WAHAT DAKHLA",
    "WAHAT KHARGA", "WARDIYAN", "ZAGAZIG", "ZAMALEK", "ZAWYA", "ZAWYA EL HAMRA", "ZEFTA", "ZEITOUN", "ZIZINIA",
]

IRAQ = [
    "BAGHDAD", "BASRA", "ERBIL", "MANSOUR", "NAJAF", "RUSTUMIA", "SULEIMANIYA", "TAJI", "UMM QASR",
]

JORDAN = [
    "ALKARAK INDUSTRIAL ESTATE", "ALMWAQQAR", "ALQATRANA", "AMMAN", "AQABA", "DEAD SEA", "IRBID",
    "MWAFFAQ ALSALTI AIRBASE", "ZARKA"
]

KUWAIT = [
    "ABBASIYA", "ABDALLY", "ABDULLA AL SALEM", "ABDULLAH MUBARAK", "ABRAK KHEITAN", "ABU AL HASANIA", "ABU FATIRA",
    "ABU HALIFA", "ADAN", "ADELIYA", "AHMADI", "AHMED AL JABER AIRBASE", "AL ABDALY", "AL AYOUN", "AL BIDAA",
    "AL FUNNAYHIL", "AL MASAYEEL", "AL NASEEM", "AL QASAR", "AL RAI", "AL TAIMA", "AL WAHA", "ALI AL SALEM AIR BASE",
    "ALI SABAH AL SALEM", "AMGHARA", "ANDALUS", "ARDIYA", "ASHWAQ QURAIN", "BAYAN", "BNEID AL GAR", "CAMP ARIFJAN",
    "CAMP BUEHRING", "DAHER", "DAIYA", "DAJEEJ", "DARWAZA", "DASMA", "DASMAN", "DOHA", "EGAILA", "FAHAD AL AHMAD",
    "FAHAHEEL", "FAIHA", "FARWANIYA", "FINTAS", "FIRDOUS", "FUNANTEES", "GARNATA", "HADIYA", "HAWALLY", "HITTEEN",
    "ISHBILYA", "JABER AL AHMAD", "JABER AL ALI", "JABRIYA", "JAHRA", "JLEEB AL SHUYOUKH", "JULIAH", "KABD", "KEIFAN",
    "KHALDIYA", "KHEIRAN", "KUWAIT CITY", "MAHBOULA", "MAIDAN HAWALLY", "MALIYA", "MANGAF", "MANSOURIYA", "MESSILA",
    "MINA ABDULLA", "MINA AHMADI", "MINA AL ZOUR", "MIRGAB", "MISHREF", "MUBARAK ABDULLAH", "MUBARAK AJ JABAR SUBURB",
    "MUBARAK AL KABEER", "MUBARAKIYA", "NAHDA", "NIGRA", "NUZHA", "OMARIYA", "QADSIYA", "QAIRAWAN", "QIBLA", "QOSOOR",
    "QURAIN", "RABIYA", "RAWDAH", "REHAB", "RIGGAE", "RIKKA", "RUMAITHIYA", "SAAD AL ABDULLAH", "SABAH AL AHMED",
    "SABAH AL NASER", "SABAH AL SALEM", "SABAHIYA", "SABHAN", "SABIYA", "SAFAT", "SAHID AL WAZIM", "SALAM", "SALHIYA",
    "SALMIYA", "SALWA", "SAWABER", "SHAAB", "SHAAB AL BAHRI", "SHAMIYA", "SHARQ", "SHUAIBA", "SHUHADA", "SHUWAIKH",
    "SHUWAIKH FREE TRADE ZONE", "SIDDIQ", "SOUTH SURRA", "SUBIYA", "SULAIBIKHAT", "SULAIBIYA", "SURRA", "UM AL AISH",
    "UM AL HAIMAN", "WAFRA", "YARMOUK", "ZAHRA",
]

LEBANON = [
    "ALEY", "BAABDA", "BAALBECK", "BATROUN", "BECHARRE", "BEIRUT", "BINT JBEIL", "CHOUF", "CHTAURA", "HASBAYA",
    "HERMEL", "JBEIL", "JEZZINE", "JOUNIEH", "KESEROUAN", "KOURA", "MARJEEYOUN", "METN", "MINIEH-DENNIYE", "NABATIEH",
    "RACHAYA", "SAIDA", "TRIPOLI", "TYRE", "WEST BEKAA", "ZAHLE", "ZGHARTA",
]

LIBYA = [
    "AL ABYAR", "AL AGOUIRA", "AL BEIDA", "AL BREGA", "AL JOUFRA", "AL KHOUMS", "AL KOUFRA", "AL KOUTFRA", "AL MARGE",
    "AL ZAWYIA", "BENGHAZI", "BENINA", "DAMA", "EGDABIYA", "GERIAN", "GHARYAN", "GIMINIS", "JADO", "JALO", "MARADA",
    "MERADA", "MESRATA", "MISURATA", "MORZOK", "MOURZUK", "NALOUTE", "OUBARI", "SABHA", "SABRATA", "SHAHAT", "SIRTE",
    "SOULOUG", "SOURMAN", "SRTE", "TARHOUNA", "TOUBRUK", "TRIPOLI", "WADAN", "ZLITEN", "ZWARA",
]

MOROCCO = [
    "AGADIR", "AIN EL AOUDA", "AIN HARROUDA", "ARHBALA", "BENI MELLAL", "BERRECHID", "BOUKNADEL", "BOUSKOURA",
    "BOUZNIKA", "CASABLANCA", "CHEMAIA", "DAR BOUAZZA", "DAR OULD ZIDOUH", "EL JADIDA", "EL MENZEH", "ESSAOUIRA",
    "FES", "GHORM EL ALEM", "GUETTAYA", "HAD SOUALEM", "HAOUZIA", "JORF LASFAR", "KASBA TADLA", "KENITRA", "KENITRA",
    "KHATT AZAKARNE", "KHMIS NGA", "LAAYOUNE", "LARACHE", "MARRAKECH", "MEDIOUNA", "MEKNES", "MOHAMMEDIA", "NOUACEUR",
    "NOUACEUR BEN ABID", "OUJDA", "OULED YAICHE", "RABAT", "SAFI", "SALE", "SEBT GZOULA", "SIDI BOUZID", "SKHIRAT",
    "TAGHZIRT", "TANGER", "TEMARA", "TETOUAN", "TNINE RHIATE",
]

OMAN = [
    "AL ANSAB", "AL KHOUD", "AL KHUWAIR", "AZAIBA", "BARKA", "BOSHAR", "CBD AREA", "DARSAIT", "GHALA", "GHUBRAH",
    "HAMRIYA", "JIBROO", "MABELA", "MADINAT AL ALAM", "MADINAT QABOOS", "MARBAT", "MEDINAT QABOOS", "MINA AL FAHAL",
    "MINISTRY AREA", "MUSCAT", "MUTTRAH", "MUWALAH", "QURUM", "QURUM HEIGHTS", "RAYSUT", "RUSAIL", "RUWI", "SALALAH",
    "SEEB", "SHATTI QURUM", "SOHAR", "THUMRAIT", "WADI ADAI", "WADI KEBIR", "WATTAYAH",
]

QATAR = [
    "AL KHOR", "AL SHAMAL", "AL UDEID", "DOHA", "DOHA, ABU NAKLA", "DOHA, ABU SIDRA", "DOHA, AL DAFNA", "DOHA, AL DAYEEN",
    "DOHA, AL DUHAIL", "DOHA, AL GHARAFA", "DOHA, AL GHUWAIRIYA", "DOHA, AL HILAL", "DOHA, AL KEESHA", "DOHA, AL KHARATIYAT",
    "DOHA, AL KHULAIFAT", "DOHA, AL KHUWAIR", "DOHA, AL LUQTA", "DOHA, AL MESSILA", "DOHA, AL RUWAIS", "DOHA, AL SAAD",
    "DOHA, AL SAILIYA", "DOHA, AL SHAKAMA", "DOHA, AL THAKHIRA", "DOHA, AL WAAB", "DOHA, AL WAJBA", "DOHA, AL WAKRA",
    "DOHA, ALMANSOURA", "DOHA, AZIZYA", "DOHA, BANI HAJER", "DOHA, BIN MAHMOUD", "DOHA, BUHAMOUR", "DOHA, DAHL AL HAMAM",
    "DOHA, FAREEJ AL AMIR", "DOHA, FEREEJ AL AMIR", "DOHA, FEREEJ AL KULAIB", "DOHA, FEREEJ AL NASR", "DOHA, FEREEJ BIN DERHAM",
    "DOHA, GHARRFA", "DOHA, HAMAD INTL AIRPORT", "DOHA, HAZM AL MARKHIYA", "DOHA, INDUSTRIAL AREA", "DOHA, IZGHAWA",
    "DOHA, JEBAILAT", "DOHA, JELAIAH", "DOHA, JEMALIYA", "DOHA, KHULAIFATH", "DOHA, LUSAIL", "DOHA, MADHINAT KHALIFA",
    "DOHA, MAMOURA", "DOHA, MANASEER", "DOHA, MARKHAYA", "DOHA, MESAIEED", "DOHA, MESAIMEER", "DOHA, MESSILA", "DOHA, MUAITHER",
    "DOHA, MUSHERIEB", "DOHA, NAJMA", "DOHA, NEW AL RAYYAN", "DOHA, NEW INDUSTRIAL AREA", "DOHA, NEW SALATA", "DOHA, NUAIJA",
    "DOHA, OLD AIRPORT", "DOHA, OLD AL RAYYAN", "DOHA, ONAIZA", "DOHA, PEARL QATAR", "DOHA, RAS ABU ABBOUD", "DOHA, RAS ABU FONTAS",
    "DOHA, RAWDA AL - KHAIL", "DOHA, RAWDAT RASHEED", "DOHA, RAWDATH AL HAMMAMA", "DOHA, RUMAILA", "DOHA, SAHA", "DOHA, SHAHANIYA",
    "DOHA, SHAMAL", "DOHA, SPORTS CITY", "DOHA, THUMAMA", "DOHA, UMM AL AMAD", "DOHA, UMM AL SANEEM", "DOHA, UMM BAB",
    "DOHA, UMM GARN", "DOHA, UMM GHUWAILINA", "DOHA, UMM LEKHBA", "DOHA, UMM SAID", "DOHA, UMM SLAL ALI", "DOHA, UMM SLAL MOHAMMAD",
    "DOHA, WADI AL BANAT", "DOHA, WESTBAY", "DOHA, WUKAIR", "DUKHAN", "DUKHAN, AL NASRANIYA", "DUKHAN, ZEKREET INTERCHANGE",
    "RAS LAFFAN", "RAS LAFFAN INDUSTRIAL CITY",
]

ARAB_EMIRATES = [
    "ABU DHABI", "ABU DHABI CITY", "ABU HAIL, DUBAI", "AFLAJ, AL AIN", "AJMAN", "AJMAN CITY", "AL AAHAD", "AL ABRAQ",
    "AL AIN", "AL AIN AIRPORT, AL AIN", "AL AIN CITY", "AL AIN DAIRY FARM, AL AIN", "AL ANDALUS COMPOUND, AL AIN",
    "AL AQAA", "AL ATTAIN", "AL AWEER", "AL BARARI", "AL BARASHI", "AL BARSHA", "AL BARSHA SOUTH", "AL BASRA, AL AIN",
    "AL BURAIRAT", "AL DAR AL BAIDA", "AL DHAFRA", "AL DHAFRA AB", "AL DHAFRA AIR BASE AE", "AL DHAID -FUJAIRAH",
    "AL DHAIT", "AL DHAIT NORTH", "AL DHAIT SOUTH", "AL DIGDAGA", "AL DIYAFA", "AL FALLAH", "AL FURJAN", "AL GARHOUD",
    "AL GHAIL INDUSTRIAL PARK", "AL GHUSAIS", "AL GHUSAIS INDUSTRIAL AREA", "AL HADITHA", "AL HAIL INDISTRIAL AREA",
    "AL HAWIYAH", "AL HAZZAN", "AL HILI, AL AIN", "AL HUDAIBAH", "AL HUMRAH", "AL JADDAF", "AL JAHLI, AL AIN",
    "AL JIMI, AL AIN", "AL KHABISI, AL AIN", "AL KHARRAN", "AL KHATEM", "AL KHAWANEEJ", "AL KHOR", "AL KHUBASI",
    "AL KHUZAM", "AL KUWAITAT, AL AIN", "AL LAYAN", "AL MADAR", "AL MAIDEN", "AL MAIRID", "AL MAMOURAH",
    "AL MANASEER, AL AIN", "AL MARKAZ IND. PARK ABU DHABI", "AL MARYAH ISLAND", "AL MISBAH, AL AIN",
    "AL MNAIZFAH, AL AIN", "AL MNAIZLAH, AL AIN", "AL MURABBA, AL AIN", "AL MUTAWAA, AL AIN", "AL MUWAIJI, AL AIN",
    "AL NAHDA 1", "AL NAKEEL", "AL NAKHEEL", "AL OWAINAH, AL AIN", "AL QUAWASIM CORNICHE", "AL QUOZ", "AL RAHA",
    "AL RAHA BEACH AREA", "AL RAHMANIYA", "AL RAMLAH", "AL RAMS ROAD", "AL RAS", "AL RAUDAH", "AL RIGGA", "AL RIQQAH",
    "AL RUMAILAH, AL AIN", "AL RUWAIKAH, AL AIN", "AL SAJJA", "AL SALAMAH", "AL SANAIYA, AL AIN", "AL SAROOJ, AL AIN",
    "AL SHAREJ, AL AIN", "AL SILA", "AL SOFOUH GARDENS", "AL TAWAM, AL AIN", "AL TOWAYYA, AL AIN", "AL TWAR",
    "AL URAIBI", "AL WAHA", "AL WARQA", "AL WARSAN", "AL ZAHRA", "ARABIAN RANCHES", "ASHAREJ, AL AIN", "AYAL NASIR",
    "BADA ZAYED, ABU DHABI", "BARAKA, ABU DHABI", "BARSHA HEIGHTS", "BAWADI MALL, AL AIN", "BEDA ZAYED", "BIDYA",
    "BUR DUBAI", "BUSINESS BAY", "CITY OF ARABIA", "CIVIC CENTRE, AL AIN", "CMC DUBAI", "CMC, DUBAI",
    "COLOAD DROP OFF DEIRA", "DAHAN", "DEIRA", "DEIRA D.O, DUBAI", "DIBBA", "DIBBA AL HOSN", "DISCOVERY GARDENS",
    "DOWNTOWN DUBAI", "DOWNTOWN JEBEL ALI", "DUBAI", "DUBAI ACADEMIC CITY", "DUBAI AIRPORT FREEZONE", "DUBAI AIRPORT T2",
    "DUBAI DESIGN DISTRICT", "DUBAI HEALTH CARE CITY", "DUBAI HUMANITARIAN CITY", "DUBAI INDUSTRIAL CITY",
    "DUBAI INTERNATIONAL FIN. CENTER", "DUBAI INTERNET CITY", "DUBAI INVESTMENT PARK", "DUBAI KNOWLEDGE PARK",
    "DUBAI KNOWLEDGE VILLAGE", "DUBAI LAND", "DUBAI LOGISTIC CITY", "DUBAI MARINA", "DUBAI MARITIME CITY",
    "DUBAI MEDIA CITY", "DUBAI MOTOR CITY", "DUBAI OUTSOURCE ZONE", "DUBAI SILICON OASIS", "DUBAI SPORTS CITY",
    "DUBAI STUDIO CITY", "DUBAI WATER FRONT", "DUBAI WORLD CENTRAL - LOGISTIC", "DUBAI, JEBEL ALI FREE ZONE",
    "EMIRATES HILLS", "EMIRATES LAKES", "FALAJ HAZZAA, AL AIN", "FALCON CITY OF WONDERS", "FASEEL", "FESTIVAL CITY",
    "FRIJ AL MURAR", "FUJAIRAH", "FUJAIRAH AIRPORT", "FUJAIRAH CITY", "FUJAIRAH FREE ZONE", "FUJAIRAH PORT", "GARDENS",
    "GHAYATHI, ABU DHABI", "GHUWAIFAT, ABU DHABI", "GREEN COMMUNITY", "HAMIM, ABU DHABI", "HAMRIYA", "HAMRIYA FREE ZONE",
    "HAMRIYA PORT", "HATTA, DUBAI", "HILI AL KHALEEF, AL AIN", "HILI OASIS, AL AIN", "HILI SANAIYA, AL AIN", "HOR AL ANZ A",
    "ICAD-1", "ICAD-11", "ICAD-111", "INDUSTRIAL AREA", "INDUSTRIAL PARK", "INSIDE MEENA PORT", "INTERNATIONAL CITY",
    "INTERNATIONAL MEDIA PROD. ZONE", "JAFLIYA", "JAFZA, DUBAI", "JAZEERAH AL HAMRA", "JEBEL ALI", "JEBEL ALI FREE ZONE",
    "JEBEL ALI FREE ZONE, DUBAI", "JEBEL ALI FREE ZONE, NORTH", "JEBEL ALI FREE ZONE, SOUTH", "JEBEL ALI INDUSTRIAL AREA",
    "JEBEL DHANNA, ABU DHABI", "JUMEIRA", "JUMEIRAH BEACH RESIDENCE", "JUMEIRAH ISLAND", "JUMEIRAH LAKE TOWERS",
    "JUMEIRAH VILLAGE", "JUMEIRAH VILLAGE CIRCLE", "JUMEIRAH VILLAGE TRIANGLE", "KALBA", "KARAMA", "KHALIFA CITY",
    "KHALIFA CITY A", "KHALIFA CITY B", "KHALIFA PARK AREA", "KHOR KHEIR", "KHOR KHWAIR", "KHORFAKAN", "KHORFAKKAN",
    "MADAM, DUBAI", "MAFRAQ", "MAIN STREET AL AIN, AL AIN", "MAMZAR", "MANKOOL", "MASAFI", "MEENA BAZAR", "MEYDAN",
    "MINA ZAYED", "MIRDIF", "MIRFA, ABU DHABI", "MIZHER", "MOHAMMED BIN ZAYED CITY", "MREIFIA, AL AIN", "MUDUN",
    "MURAQQABAT", "MURBA", "MURSHID BAZAR", "MUSAFFAH", "MUSSAFAH", "MUSSAFAH SHABIYA", "MUTEENA", "NAD AL HAMAR",
    "NAD AL SHEBA MEYDAN", "NAKHEEL", "NEW AL KUWAITAT, AL AIN", "NEW AL SAROOJ, AL AIN", "NEYADAT, AL AIN",
    "OUD AL TOUBA, AL AIN", "OUD MUTEENA", "PALM ISLAND", "PORT SAEED", "Q POINT AL MAZAYA", "QIDFA", "QUSAIDAT",
    "RAK CITY", "RAK CORNICHE", "RAS AL KHAIMAH", "RAS AL KHAIMAH AIRPORT", "RAS AL KHAIMAH CITY",
    "RAS AL KHAIMAH MARITIME CITY", "RAS AL KHOR", "RASHIDIYA", "REEM ISLAND", "REMRAAM", "RIGGA AL BUTEEN", "RUWAIS",
    "RUWAIS, ABU DHABI", "SATWA", "SHABIYA KHALIFA, AL AIN", "SHAHAMA", "SHARJAH", "SHARJAH CITY", "SHARJAH FREE ZONE",
    "SHARJAH INTERNATIONAL AIRPORT", "SHARJAH, AL RAAS", "SILA, ABU DHABI", "SONAPUR", "SOOWAH ISLAND",
    "SWEIHAN, ABU DHABI", "TARIF, ABU DHABI", "TECHNO PARK", "THE GREENS", "THE MEADOWS", "THE SPRINGS", "THE VILLA",
    "TOWN CENTRE, AL AIN", "UMM AL NAR", "UMM AL QUWAIN", "UMM RAMOOL", "UMM-AL QUWAIN", "WATHABA", "YAS ISLAND EAST",
]

CITY_CODES = {
    'SA': {
        **SA,
        **{city.capitalize(): city for city in SA.values()},
    },
    'BH': {city.capitalize(): city for city in BAHRAIN},
    'EG': {city.capitalize(): city for city in EGYPT},
    'IQ': {city.capitalize(): city for city in IRAQ},
    'JO': {city.capitalize(): city for city in JORDAN},
    'KW': {city.capitalize(): city for city in KUWAIT},
    'LB': {city.capitalize(): city for city in LEBANON},
    'LY': {city.capitalize(): city for city in LIBYA},
    'MA': {city.capitalize(): city for city in MOROCCO},
    'OM': {city.capitalize(): city for city in OMAN},
    'QA': {city.capitalize(): city for city in QATAR},
    'AE': {city.capitalize(): city for city in ARAB_EMIRATES},
}


class CityCodeNotFound(Exception):
    pass


def get_city_code(country, cities):
    if country in CITY_CODES:
        for city in cities:
            city_code = CITY_CODES[country].get(city.capitalize())
            if city_code:
                return city_code
    raise CityCodeNotFound()
