CITY_ROUTE_MAPPING = {
    'aba alworood': 'R2',
    'abha': 'S',
    'abqaiq': 'D9',
    'abu ajram': 'R8',
    'abu areish': 'S4',
    'ad dahinah': 'R3',
    'ad dubaiyah': 'R7',
    'afif': 'R4',
    'aflaj': 'R10',
    'ahad masarha': 'S7',
    'ahad rufaidah': 'S',
    'ain dar': 'D9',
    'al adari': 'R8',
    'al ais': 'J4',
    'al ajfar': 'R6',
    'al ammarah': 'R2',
    'al ardah': 'S2',
    'al arja': 'R4',
    'al asyah': 'R2',
    'al bada': 'J5',
    'al batra': 'R2',
    'al bijadyah': 'R4',
    'al dalemya': 'R2',
    'al fuwaileq': 'R2',
    'al hait': 'R6',
    'al haith': 'R6',
    'al hassa': 'D3',
    'al hayathem': 'R7',
    'al hufayyirah': 'R4',
    'al hulayfah as sufla': 'R6',
    'al idabi': 'S2',
    'al khishaybi': 'R2',
    'al khitah': 'R6',
    'al laqayit': 'R8',
    'al mada': 'S',
    'al mahd': 'J2',
    'al midrij': 'R2',
    'al qarin': 'R4',
    'al wasayta': 'R6',
    'al-jsh': 'D3',
    'alghat': 'R3',
    'alhada': 'J3',
    'alnabhanya': 'R2',
    'alrass': 'R2',
    'amaq': 'J7',
    'an nabk abu qasr': 'R8',
    'an nafiah': 'R4',
    'an nuqrah': 'R6',
    'anak': 'D5',
    'aqiq': 'J6',
    'ar radifah': 'R8',
    "ar rafi'ah": 'R8',
    'ar rishawiyah': 'R2',
    'arar': 'R9',
    'artawiah': 'R3',
    'as sulaimaniyah': 'R8',
    'as sulubiayh': 'R2',
    'asfan': 'J8',
    'ash shaara': 'R4',
    'ash shamli': 'R6',
    'ash shananah': 'R6',
    'ash shimasiyah': 'R2',
    'ash shuqaiq': 'J7',
    'at tuwayr': 'R8',
    'atawleh': 'J6',
    'ath thybiyah': 'R5',
    'awamiah': 'D5',
    'ayn fuhayd': 'R2',
    'badaya': 'R2',
    'bader': 'J2',
    'badr al janoub': 'S',
    'baha': 'J6',
    'bahara': 'J',
    'bahrat al moujoud': 'J1',
    'balahmar': 'S',
    'balasmar': 'S',
    'balqarn': 'S',
    'baqa ash sharqiyah': 'R6',
    'baqaa': 'R6',
    'baqiq': 'D1',
    'bareq': 'S',
    'batha': 'D2',
    'biljurashi': 'J6',
    'birk': 'J7',
    'bish': 'S6',
    'bisha': 'S1',
    'bukeiriah': 'R2',
    'buraidah': 'R2',
    'daelim': 'R',
    'damad': 'S2',
    'dammam': 'D2',
    'darb': 'S6',
    'dariyah': 'R2',
    'deraab': 'R',
    "dere'iyeh": 'R',
    'dhahban': 'J',
    'dhahran': 'D1',
    'dhahran al janoob': 'S',
    'dhurma': 'R',
    'domat al jandal': 'R8',
    'duba': 'J5',
    'duhknah': 'R2',
    'dulay rashid': 'R2',
    'farasan': 'S8',
    'ghazalah': 'R6',
    'ghtai': 'R6',
    'gilwa': 'J6',
    'gizan': 'S2',
    'hadeethah': 'R1',
    'hafer al batin': 'R5',
    'hail': 'R6',
    'halat ammar': 'J5',
    'haqil': 'J5',
    'harad': 'D3',
    'hareeq': 'R',
    'harjah': 'S',
    'hawea/taif': 'J3',
    'hawtat bani tamim': 'R',
    'hazm al jalamid': 'R9',
    'hedeb': 'R8',
    'hinakeya': 'J2',
    'hofuf': 'D3',
    'horaimal': 'R',
    'hotat sudair': 'R3',
    'huraymala': 'R',
    "ja'araneh": 'J1',
    'jafar': 'D3',
    'jalajel': 'R3',
    'jeddah': 'J',
    'jouf': 'R8',
    'jubail': 'D4',
    'jumum': 'J1',
    'kahlah': 'R2',
    'kara': 'R8',
    "kara'a": 'S',
    'karboos': 'S7',
    'khafji': 'D6',
    'khaibar': 'J2',
    'khairan': 'R10',
    'khamaseen': 'R10',
    'khamis mushait': 'S',
    'kharj': 'R7',
    'khasawyah': 'S4',
    'khobar': 'D1',
    'khodaria': 'D2',
    'khulais': 'J8',
    'khurma': 'J9',
    'king khalid military city': 'R5',
    'kubadah': 'R2',
    'laith': 'J7',
    'layla': 'R10',
    'madinah': 'J2',
    'mahad al dahab': 'J2',
    'majarda': 'S',
    'majma': 'R3',
    'makkah': 'J1',
    'mandak': 'J6',
    'mastura': 'J8',
    'mawqaq': 'R6',
    'midinhab': 'R2',
    'mikhwa': 'J6',
    'mohayel aseer': 'S',
    'moqaq': 'R6',
    'mrat': 'R3',
    'mubaraz': 'D3',
    'mubayid': 'R3',
    'mulaija': 'D3',
    'mulayh': 'R3',
    'munifat al qaid': 'R6',
    'muthaleif': 'J7',
    'muzahmiah': 'R',
    'muzneb': 'R2',
    'nabiya': 'D2',
    'najran': 'S3',
    'namas': 'S',
    'nimra': 'J6',
    'nisab': 'R5',
    'noweirieh': 'D6',
    'nwariah': 'J1',
    'ojam': 'D3',
    'onaiza': 'R2',
    'othmanyah': 'D3',
    'oula': 'J2',
    'oyaynah': 'R',
    'oyoon al jawa': 'R2',
    'qahmah': 'J7',
    'qarah': 'D3',
    'qariya al olaya': 'D6',
    'qasab': 'R3',
    'qassim': 'R2',
    'qatif': 'D5',
    'qaysoomah': 'R5',
    'qbah': 'R2',
    'qufar': 'R6',
    'qunfudah': 'J7',
    'qurayat': 'R1',
    'qusayba': 'R2',
    "quwei'ieh": 'R',
    'rabigh': 'J8',
    'rafha': 'R5',
    'rahima': 'D5',
    'rania': 'J10',
    'ras al kheir': 'D4',
    'ras tanura': 'D8',
    'rawdat habbas': 'R5',
    "rejal alma'a": 'S',
    'remah': 'R',
    'riyadh': 'R',
    'riyadh al khabra': 'R2',
    'rowdat sodair': 'R3',
    'rvaya aljamsh': 'R4',
    'rwaydah': 'R',
    'sabt el alaya': 'S',
    'sabya': 'S5',
    'sadyan': 'R6',
    'safanyah': 'D6',
    'safwa': 'D2',
    'sahna': 'R',
    'sajir': 'R4',
    'sakaka': 'R8',
    'salbookh': 'R',
    'salwa': 'D2',
    'samtah': 'S7',
    'saqf': 'R2',
    'sarar': 'D6',
    'sarat obeida': 'S',
    'seihat': 'D7',
    'shaqra': 'R3',
    'shari': 'R2',
    'sharourah': 'S3',
    "shefa'a": 'R',
    'shinanh': 'R6',
    'shoaiba': 'J',
    "shraie'e": 'J1',
    'shumeisi': 'J1',
    'simira': 'R6',
    'subheka': 'S',
    'sulaiyl': 'R10',
    'suwayr': 'R8',
    'tabrjal': 'R8',
    'tabuk': 'J5',
    'taiba': 'J',
    'taif': 'J3',
    'tanda': 'S',
    'tanjeeb': 'D6',
    'tanuma': 'S',
    'tanumah': 'R3',
    'tarut': 'D5',
    'tatleeth': 'S',
    'tayma': 'J5',
    'tebrak': 'R',
    'thabya': 'S5',
    'thadek': 'R',
    'tharmada': 'R3',
    'thebea': 'R2',
    'thumair': 'R3',
    'thuqba': 'D1',
    'towal': 'J',
    'turaib': 'S',
    'turaif': 'R9',
    'turba': 'J11',
    'udhaliyah': 'D3',
    'um aljamajim': 'R3',
    'umluj': 'J4',
    'uqlat al suqur': 'R2',
    'ushayqir': 'R3',
    'uyun': 'D3',
    'wadeien': 'S',
    'wadi bin hasbal': 'S',
    'wadi el dwaser': 'R10',
    'wadi fatmah': 'J1',
    'wajeh (al wajh)': 'J5',
    'yanbu': 'J4',
    'yanbu al baher': 'J4',
    'yanbu nakhil': 'J4',
    'zahban': 'J8',
    'zallum': 'R8',
    'zulfi': 'R3'
}


def routing_code(order):
    if order.shipping_address.country == 'SA':
        cdb_cities = [order.shipping_address.city]
        cdb_cities.extend(order.shipping_address.base_cities)
        for city in cdb_cities:
            code = CITY_ROUTE_MAPPING.get(city.lower().strip())
            if code:
                return code
    return None
